<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends RokCommon_Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('rokgallery_slices', 'thumb_xsize', 'integer', '4', array(
             'unsigned' => '1',
             'notnull' => '1',
             ));
        $this->addColumn('rokgallery_slices', 'thumb_ysize', 'integer', '4', array(
             'unsigned' => '1',
             'notnull' => '1',
             ));
        $this->addColumn('rokgallery_slices', 'thumb_keep_aspect', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '1',
             ));
        $this->addColumn('rokgallery_slices', 'thumb_background', 'string', '12', array(
             'default' => 'transparent',
             ));
        $this->addColumn('rokgallery_slices', 'ordering', 'integer', '4', array(
             'notnull' => '1',
             'unsigned' => '1',
             ));
        $this->changeColumn('rokgallery_galleries', 'thumb_background', 'string', '12', array(
             'default' => 'transparent',
             ));
    }

    public function down()
    {
        $this->removeColumn('rokgallery_slices', 'thumb_xsize');
        $this->removeColumn('rokgallery_slices', 'thumb_ysize');
        $this->removeColumn('rokgallery_slices', 'thumb_keep_aspect');
        $this->removeColumn('rokgallery_slices', 'thumb_background');
        $this->removeColumn('rokgallery_slices', 'ordering');
    }
}