<?php

/**
 * RokGallery_Model_Base_FileViews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $file_id
 * @property integer $count
 * @property RokGallery_Model_File $File
 * 
 * @package    RokGallery
 * @subpackage models
 * @author     RocketTheme LLC <support@rockettheme.com>
 * @version    SVN: $Id$
 */
abstract class RokGallery_Model_Base_FileViews extends RokCommon_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('rokgallery_file_views');
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'unique' => true,
             'length' => '4',
             ));
        $this->hasColumn('kount as count', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RokGallery_Model_File as File', array(
             'local' => 'file_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE',
             'owningSide' => true));
    }
}