<?php

/**
 * RokGallery_Model_Base_Job
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property char $id
 * @property enum $type
 * @property string $properties
 * @property enum $state
 * @property string $status
 * @property integer $percent
 * @property string $sm
 * 
 * @package    RokGallery
 * @subpackage models
 * @author     RocketTheme LLC <support@rockettheme.com>
 * @version    SVN: $Id$
 */
abstract class RokGallery_Model_Base_Job extends RokCommon_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('rokgallery_jobs');
        $this->hasColumn('id', 'char', 36, array(
             'type' => 'char',
             'unique' => true,
             'primary' => true,
             'length' => '36',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Import',
              1 => 'Create Gallery',
              2 => 'Update Gallery',
              3 => 'Tag Addition',
              4 => 'Tag Removal',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('properties', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('state', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Prepping',
              1 => 'Ready',
              2 => 'Running',
              3 => 'Pausing',
              4 => 'Paused',
              5 => 'Completed',
              6 => 'Canceling',
              7 => 'Canceled',
              8 => 'Deleting',
              9 => 'Deleted',
              10 => 'Errored',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('status', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('percent', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => true,
             ));
        $this->hasColumn('sm', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}