<?php

/**
 * RokGallery_Model_FileViews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RokGallery
 * @subpackage models
 * @author     RocketTheme LLC <support@rockettheme.com>
 * @version    SVN: $Id: FileViews.php 39322 2011-07-02 05:20:22Z btowles $
 */
class RokGallery_Model_FileViews extends RokGallery_Model_Base_FileViews
{

}