<?php

/**
 * RokGallery_Model_FiltersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RokGallery_Model_FiltersTable extends RokCommon_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RokGallery_Model_FiltersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RokGallery_Model_Filters');
    }
}