<?php

/**
 * RokGallery_Model_Profile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RokGallery
 * @subpackage models
 * @author     RocketTheme LLC <support@rockettheme.com>
 * @version    SVN: $Id$
 */
class RokGallery_Model_Profile extends RokGallery_Model_Base_Profile
{

}