<?php

/**
 * RokGallery_Model_SliceTags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RokGallery
 * @subpackage models
 * @author     RocketTheme LLC <support@rockettheme.com>
 * @version    SVN: $Id$
 */
class RokGallery_Model_SliceTags extends RokGallery_Model_Base_SliceTags
{

}